### ISSUE TITLE
Créer le site https://fr.nuxtjs.org/

### ISSUE THREAD

**Issue by MachinisteWeb** [vuejs-fr/nuxt#16]
Une fois que les fichiers dans Guide seront revu, il sera intéressant de monter le site 
— https://fr.nuxtjs.org/ en ligne
sans mettre de lien vers celui-ci dans le menu des sites officiels de https://www.nuxtjs.org/ éventuellement.

L'idée est de faire comme pour Vue.js, à savoir que tout le temps ou les parties autres que les fichiers Essentiels était en cours de tradduction, les liens de navigation indiquait (En) pour les pages concernée, et en haut de chaque page un cadre expliquait que la page en question était en cours de traduction et invitait qui le souhaitait à participer à cette traduction.

Cela permettait de commencer au site à se faire référencer sur les réseaux et à ceux tombant sur les pages « avancées » ou « l'API » toujours en état de traduction de pouvoir aider !

Que puis-je faire pour aider à cela @Atinux ? Dois-je mettre en place un environnement particulier sur GitHub avec un CNAME vers https://fr.nuxtjs.org/ ?

Ça presse pas, je prends de l'avance histoire que le site soit up dès que le Guide sera totalement revu déjà (ce qui va arrivé assez tôt finalement :) )

**Comment by atinux** [comment]
@Haeresis ce sera assez rapide a mettre en place, j'aurai juste a deployer nuxtjs.org avec un sous-domaine `fr.nuxtjs.org` et "activer" le sous-domain `fr` pour la langue.

Il faudra quand même "merge" le dossier `fr/` dans `nuxt/docs` afin que l'API soient a jour et ajouter une alerte dans les fichiers Markdown qui ne seront pas traduit :)

**Comment by MachinisteWeb** [comment]
Top ! Donc rien a faire de notre côté pour cette mise en place ;) Merci ! On s'en remet à toi !

**Comment by atinux** [comment]
@Haeresis il faudra juste me le rappeler quand on fera le premier merge du dossier `fr/` sur `nuxt/docs` :)

**Comment by MachinisteWeb** [comment]
Ça devrait pouvoir ce faire :)
