### ISSUE TITLE
Relecture de la partie FAQ

### ISSUE THREAD

**Issue by MachinisteWeb** [vuejs-fr/nuxt#23]
J'étais pas très réveillé ce matin du coup j'ai commit sur la branche working :(

Je vous laisse faire vos retours de traduction sur le commit en lui-même et j'ouvrirais une PR avec le delta entre cette PR et le working actuel !

— https://github.com/vuejs-fr/nuxt/commit/ee05137666a0d5429596c05d000653ec36eefa72

**Comment by rspt** [comment]
Et voilà :)

**Comment by forresst** [comment]
Moi aussi ;-) J'ai fait les commentaires directement dans le commit

**Comment by MachinisteWeb** [comment]
Top ! La suite ici ! https://github.com/vuejs-fr/nuxt/pull/24
